package com.example;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.encoder.PatternLayoutEncoder;
import ch.qos.logback.classic.spi.Configurator;
import ch.qos.logback.classic.tyler.TylerConfiguratorBase;
import ch.qos.logback.core.ConsoleAppender;
import ch.qos.logback.core.FileAppender;
import ch.qos.logback.core.boolex.ExpressionPropertyCondition;

/**
 *
 * <p>This file was generated by logback-tyler version null</p>
 *
 * <p>Eventual errors and warnings are appended at the end.</p>
 *
 * <p>You may experiment with logback.xml to Java translation, i.e.
 * TylerConfigurator generation, at the following URL:</p>
 *
 * <p>     https://logback.qos.ch/translator/services/xml2Java.html </p>
 *
 * <p>This generated TylerConfigurator class is intended to be copied and integrated
 * into the user's project as a custom configurator. It will configure logback
 * without XML. You are free to rename TylerConfigurator as you wish.</p>
 *
 * <p>It requires logback-classic version 1.5.20 or later at runtime.</p>
 *
 * <p>Custom configurators are looked up via Java's service-provide facility. If a
 * custom provider is found, it takes precedence over logback's own configurators,
 * e.g. DefaultJoranConfigurator.</p>
 *
 * <p>To install your custom configurator to your project, add a
 * provider-configuration file to the following path:</p>
 *
 * <pre>  META-INF/services/ch.qos.logback.classic.spi.Configurator</pre>
 *
 * <p>This provider-configuration file should contain a line with the fully
 * qualified class name of your tyler configurator.</p>
 *
 * <p>See also item 1 of 'Configuration at initialization' section at </p>
 *
 * <p>  https://logback.qos.ch/manual/configuration.html#auto_configuration</p>
 *
 * <p>Configurations using TylerConfigurator can still dynamically configure
 * logger levels with the help of properties files. Moreover, configuration
 * files in properties format can be watched for changes. See the
 * documentation on PropertiesConfigurator for more details.</p>
 *
 * <p>https://logback.qos.ch/manual/configuration.html#propertiesConfigurator</p>
 *
 * <p>Please note that when logback-tyler transforms XML to Java, it performs
 * runtime analysis of classes using Java's class reflection. Thus,
 * if your logback.xml mentions classes which are not on the classpath,
 * logback-tyler will fail during the translation.</p>
 *
 */
public class TylerConfigurator extends TylerConfiguratorBase implements Configurator {
    /**
     * Appender variable referencing the appender named "FILE".
     */
    protected FileAppender appenderFILE;

    /**
     * Appender variable referencing the appender named "CON".
     */
    protected ConsoleAppender appenderCON;

    /**
     * Variable used in conditional processing
     */
    protected ExpressionPropertyCondition expressionPropertyCondition_0;

    /**
     * <p>This method performs configuration per {@link Configurator} interface.</p>
     *
     * <p>If <code>TylerConfigurator</code> is installed as a configurator service, this
     * method will be called by logback-classic during initialization.</p>
     */
    @Override
    public Configurator.ExecutionStatus configure(LoggerContext loggerContext) {
        setContext(loggerContext);
        addOnConsoleStatusListener();
        this.expressionPropertyCondition_0 = setupExpressionPropertyCondition_0();
        if(this.expressionPropertyCondition_0.evaluate()) {
            this.appenderCON = setupAppenderCON();
            Logger logger_ROOT = setupLogger("ROOT", null, null);
            logger_ROOT.addAppender(appenderCON);
        } else {
            this.appenderFILE = setupAppenderFILE();
            Logger logger_ROOT = setupLogger("ROOT", "ERROR", null);
            logger_ROOT.addAppender(appenderFILE);
        }
        return ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY;
    }

    /**
     * Setup method for expressionPropertyCondition_0
     */
    ExpressionPropertyCondition setupExpressionPropertyCondition_0() {
        ExpressionPropertyCondition propertyCondition = new ExpressionPropertyCondition();
        propertyCondition.setContext(context);
        propertyCondition.setExpression("isNull(\"environment\") && propertyEquals(\"HOSTNAME\", \"torino\")");

        propertyCondition.start();
        return propertyCondition;
    }

    ConsoleAppender setupAppenderCON() {
        ConsoleAppender appender = new ConsoleAppender();
        appender.setContext(context);
        appender.setName("CON");

        // Configure component of type PatternLayoutEncoder
        PatternLayoutEncoder patternLayoutEncoder = new PatternLayoutEncoder();
        patternLayoutEncoder.setContext(context);
        patternLayoutEncoder.setPattern("%d %-5level %logger{35} -%kvp- %msg %n");
        patternLayoutEncoder.setParent(appender);
        patternLayoutEncoder.start();
        // Inject component of type PatternLayoutEncoder into parent
        appender.setEncoder(patternLayoutEncoder);

        appender.start();
        return appender;
    }

    FileAppender setupAppenderFILE() {
        FileAppender appender = new FileAppender();
        appender.setContext(context);
        appender.setName("FILE");
        appender.setFile(subst("${randomOutputDir}/conditional.log"));

        // Configure component of type PatternLayoutEncoder
        PatternLayoutEncoder patternLayoutEncoder = new PatternLayoutEncoder();
        patternLayoutEncoder.setContext(context);
        patternLayoutEncoder.setPattern("%d %-5level %logger{35} -%kvp- %msg %n");
        patternLayoutEncoder.setParent(appender);
        patternLayoutEncoder.start();
        // Inject component of type PatternLayoutEncoder into parent
        appender.setEncoder(patternLayoutEncoder);

        appender.start();
        return appender;
    }
}
// 15:32:52,721 |-INFO in ch.qos.logback.tyler.base.handler.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
// 15:32:52,722 |-INFO in ch.qos.logback.tyler.base.handler.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
// 15:32:52,723 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@35399441 - End of configuration.
