package com.example;

import static ch.qos.logback.classic.util.LevelUtil.levelStringToLevel;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.spi.Configurator;
import ch.qos.logback.classic.tyler.TylerConfiguratorBase;
import java.net.URL;

/**
 *
 * <p>This file was generated by logback-tyler version 0.5-SNAPSHOT</p>
 *
 * <p>You can try it online at
 *
 *       https://logback.qos.ch/translator/services/xml2Java.html </p>
 *
 * <p>BEWARE: As of March 2024, TylerConfigurator generation from logback.xml
 * configuration files is still experimental and incomplete.
 * </p>
 *
 * <p>This class, i.e. TylerConfigurator, is intended to be copied and integrated
 * into the user's project as a custom configurator. It will configure logback
 * without XML.</p>
 *
 * <p>It requires logback-classic version 1.5.2 or later at runtime.</p>
 *
 * <p>Custom configurators are looked up via Java's service-provide facility. If a
 * custom provider is found, it takes precedence over logback's own configurators,
 * e.g. DefaultJoranConfigurator.</p>
 *
 * <p>See also item 1 of 'Configuration at initialization' section at
 *
 *     https://logback.qos.ch/manual/configuration.html#auto_configuration
 *
 * </p>
 */
public class TylerConfigurator extends TylerConfiguratorBase implements Configurator {
    /**
     * Stands for the 'scan' attribute of <configuration> element. Can be true, false or null.
     * If true, scanning is activated. Can be overridden by the 'scan' attribute of
     * <propertiesConfigurator> element.
     */
    protected Boolean topScan = null;

    /**
     * Since TylerConfigurator is java based, the topURL is always null.
     * However, it is still possible tos scan for changes using the
     * <propertiesConfigurator> element.
     */
    protected final URL topURL = null;

  /**
   * <p>This method performs configuration per {@link Configurator} interface.</p>
   *
   * <p>If <code>TylerConfgiurator</code> is installed as a configurator service, this
   * method will be called by logback-classic during initialization.</p>
   */
  @Override
  public Configurator.ExecutionStatus configure(LoggerContext loggerContext) {
    setContext(loggerContext);
    Logger logger_com_foo_Bar = setupLogger("com.foo.Bar", null, null);
    logger_com_foo_Bar.setLevel(levelStringToLevel(subst("${MOO_LEVEL}")));
    Logger logger_ROOT = setupLogger("ROOT", null, null);
    logger_ROOT.setLevel(levelStringToLevel("DEBUG"));
    return ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY;
  }
}
// 10:31:57,737 |-WARN in ch.qos.logback.classic.joran.action.LevelAction - <level> element is deprecated. Near [level] on line 3
// 10:31:57,737 |-WARN in ch.qos.logback.classic.joran.action.LevelAction - Please use "level" attribute within <logger> or <root> elements instead.
// 10:31:57,738 |-WARN in ch.qos.logback.classic.joran.action.LevelAction - <level> element is deprecated. Near [level] on line 7
// 10:31:57,738 |-WARN in ch.qos.logback.classic.joran.action.LevelAction - Please use "level" attribute within <logger> or <root> elements instead.
// 10:31:57,793 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@1c9b0314 - End of configuration.